DROP TABLE IF EXISTS `EVENTI`;
DROP TABLE IF EXISTS `TIMELINE`;
DROP TABLE IF EXISTS `MAPPA`;
DROP TABLE IF EXISTS `UTENTI`;

CREATE TABLE `UTENTI`
(
	ID			INT(11) AUTO_INCREMENT NOT NULL,
	Email		VARCHAR(255) NOT NULL,
	Nome		VARCHAR(255) NOT NULL,
	Cognome		VARCHAR(255) NOT NULL,
	ProfilePic	VARCHAR(255) NOT NULL,
	ProfileURL	VARCHAR(255) NOT NULL,
	LastPost	LONGTEXT NOT NULL,
	Bio			LONGTEXT,
	DataNascita	DATE,
	Sesso		CHAR(1),
	PRIMARY KEY(`ID`),
	UNIQUE(`Email`),
	UNIQUE(`Email`, `ProfilePic`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `MAPPA`
(
	Email			VARCHAR(255) NOT NULL,
	ProfilePic		VARCHAR(255) NOT NULL,
	Latitudine		DOUBLE NOT NULL,
	Longitudine		DOUBLE NOT NULL,
	UltimoAccesso	TIMESTAMP,
	PRIMARY KEY(`Email`),
	FOREIGN KEY(`Email`, `ProfilePic`) REFERENCES `UTENTI`(`Email`, `ProfilePic`)
	ON DELETE CASCADE
	ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `TIMELINE` (
	`Email`			VARCHAR(255) NOT NULL,
	`PostText`		LONGTEXT NOT NULL,
	`DataPost`		TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`MediaURL`		VARCHAR(255) DEFAULT NULL,
	`TaggedPeople`	LONGTEXT,
	`Address` 		LONGTEXT,
	PRIMARY KEY (`Email`, `DataPost`),
	FOREIGN KEY(`Email`) REFERENCES `UTENTI`(`Email`)
	ON DELETE CASCADE
	ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `EVENTI`
(
	ID				INT(11) AUTO_INCREMENT NOT NULL,
	Nome			VARCHAR(255) NOT NULL,
	Descrizione		VARCHAR(255) NOT NULL,
	Partecipanti	VARCHAR(255) NOT NULL,
	Locazione		VARCHAR(255) NOT NULL,
	Latitudine		DOUBLE NOT NULL,
	Longitudine		DOUBLE NOT NULL,
	StartTime		TIMESTAMP,
    PRIMARY KEY(`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;