DROP TABLE IF EXISTS `EVENTI`;
CREATE TABLE `EVENTI`
(
	ID				INT(11) AUTO_INCREMENT NOT NULL,
	Nome			VARCHAR(255) NOT NULL,
	Descrizione		VARCHAR(255) NOT NULL,
	Partecipanti	VARCHAR(255) NOT NULL,
	Locazione		VARCHAR(255) NOT NULL,
	Latitudine		DOUBLE NOT NULL,
	Longitudine		DOUBLE NOT NULL,
	StartTime		TIMESTAMP,
    PRIMARY KEY(`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;