-- UBI_OLD

DROP TABLE IF EXISTS `MAPPA`;
CREATE TABLE `MAPPA`
(
	Email			VARCHAR(255) NOT NULL,
	ProfilePic		VARCHAR(255) NOT NULL,
	Latitudine		DOUBLE NOT NULL,
	Longitudine		DOUBLE NOT NULL,
	UltimoAccesso	TIMESTAMP,
	PRIMARY KEY(`Email`),
	FOREIGN KEY(`Email`) REFERENCES `UTENTI`(`Email`)
	ON DELETE CASCADE
	ON UPDATE CASCADE,
	FOREIGN KEY(`ProfilePic`) REFERENCES `UTENTI`(`ProfilePic`)
	ON DELETE CASCADE
	ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;



-- PIM

CREATE TABLE `locations`
(
	user_id			INT(11) AUTO_INCREMENT NOT NULL,
        user_lat		DOUBLE NOT NULL DEFAULT 0,
        user_lon		DOUBLE NOT NULL DEFAULT 0,
        PRIMARY KEY(`user_id`),
        FOREIGN KEY(`user_id`) REFERENCES `users`(`user_id`)
	ON DELETE CASCADE
	ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;